[[bin]]
name = "lc-cli"
path = "src/main.rs"

[dependencies]
crossterm = "0.29.0"
dirs = "6.0.0"
eyre = "0.6.14"
html-to-markdown-rs = "3.12.0"
pookie = "0.1.0"
ratatui = "0.30.2"
regex = "1.13.1"
serde_json = "1.0.151"
thiserror = "2.0.20"
toml = "1.1.4"

[dependencies.clap]
features = ["derive"]
version = "4.6.6"

[dependencies.reqwest]
features = ["blocking", "json", "cookies"]
version = "0.13.4"

[dependencies.serde]
features = ["derive"]
version = "1.0.229"

[lints.rust.unexpected_cfgs]
check-cfg = ["cfg(coverage_nightly)"]
level = "warn"

[package]
edition = "2024"
name = "leetcode-cli"
version = "0.1.0"
